---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  # Enable Gateway API support in Cilium
  enable-gateway-api: "true"
  gateway-api-secrets-namespace: "kube-system"