---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hetzner-api-token
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: hcloud
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /zerotouch/prod/hetzner/api-token