#!/bin/bash
# ==============================================================================
# Platform-Controlled Tenant Service Creator
# ==============================================================================
# Purpose: Create new tenant service structure with correct registry owner
# Location: zerotouch-platform/scripts/tenants/create-tenant.sh
# Called by: zerotouch-tenants/scripts/create-tenant.sh (wrapper)
#
# Usage: 
#   ./create-tenant.sh <service-name> <tenant-repo-path> <namespace> <port> [size]
#
# Example:
#   ./create-tenant.sh my-service /path/to/zerotouch-tenants apis-myservice 8080 micro
# ==============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Arguments
SERVICE_NAME="${1:-}"
TENANT_REPO_PATH="${2:-}"
NAMESPACE="${3:-}"
PORT="${4:-8080}"
SIZE="${5:-micro}"

# Validation
if [ -z "$SERVICE_NAME" ] || [ -z "$TENANT_REPO_PATH" ] || [ -z "$NAMESPACE" ]; then
    echo -e "${RED}Usage: $0 <service-name> <tenant-repo-path> <namespace> <port> [size]${NC}"
    echo -e "${YELLOW}Example: $0 my-service /path/to/zerotouch-tenants apis-myservice 8080 micro${NC}"
    exit 1
fi

# Read ORG_NAME from tenant repo .env
TENANT_ENV="$TENANT_REPO_PATH/.env"
if [ ! -f "$TENANT_ENV" ]; then
    echo -e "${RED}✗ Error: .env not found at $TENANT_ENV${NC}"
    exit 1
fi

ORG_NAME=$(grep "^ORG_NAME=" "$TENANT_ENV" | cut -d'=' -f2 | tr -d '"' | tr -d "'")
if [ -z "$ORG_NAME" ]; then
    echo -e "${RED}✗ Error: ORG_NAME not found in $TENANT_ENV${NC}"
    exit 1
fi

echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Creating Tenant Service: $SERVICE_NAME${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
echo -e "${GREEN}✓ Service: $SERVICE_NAME${NC}"
echo -e "${GREEN}✓ Registry: ghcr.io/$ORG_NAME${NC}"
echo -e "${GREEN}✓ Namespace: $NAMESPACE${NC}"
echo -e "${GREEN}✓ Port: $PORT${NC}"
echo -e "${GREEN}✓ Size: $SIZE${NC}"
echo ""

# Paths
TENANT_DIR="$TENANT_REPO_PATH/tenants/$SERVICE_NAME"
BASE_DIR="$TENANT_DIR/base"
OVERLAYS_DIR="$TENANT_DIR/overlays"

# Create directory structure
echo -e "${BLUE}Creating directory structure...${NC}"
mkdir -p "$BASE_DIR/secrets"
mkdir -p "$BASE_DIR/claims"
mkdir -p "$OVERLAYS_DIR/dev/secrets"
mkdir -p "$OVERLAYS_DIR/staging/secrets"
mkdir -p "$OVERLAYS_DIR/production/secrets"
echo -e "${GREEN}✓ Directories created${NC}"
echo ""

# Create base kustomization.yaml
echo -e "${BLUE}Creating base kustomization...${NC}"
cat > "$BASE_DIR/kustomization.yaml" << EOF
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources for $SERVICE_NAME
resources:
# KSOPS-encrypted secrets (generated by sync-ksops-secrets.sh)
# - secrets/*.secret.yaml

# Resource claims
# - claims/dragonfly-claim.yaml
# - claims/postgres-claim.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: $SERVICE_NAME
  tenant: $SERVICE_NAME

# Common annotations
commonAnnotations:
  secrets.zerotouch.dev/provider: "ksops"
  managed-by: "zerotouch-platform"
  tenant: "$SERVICE_NAME"
EOF
echo -e "${GREEN}✓ base/kustomization.yaml${NC}"

# Create dev overlay
echo -e "${BLUE}Creating dev overlay...${NC}"
cat > "$OVERLAYS_DIR/dev/kustomization.yaml" << EOF
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base configuration
resources:
  - secrets/
  - ../../base
  - deployment.yaml
  - migration-job.yaml

# Environment-specific labels
commonLabels:
  app.kubernetes.io/instance: dev

# Namespace for this environment
namespace: $NAMESPACE
EOF
echo -e "${GREEN}✓ overlays/dev/kustomization.yaml${NC}"

cat > "$OVERLAYS_DIR/dev/deployment.yaml" << EOF
apiVersion: platform.bizmatters.io/v1alpha1
kind: AgentSandboxService
metadata:
  name: $SERVICE_NAME-sandbox
  namespace: $NAMESPACE
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  image: ghcr.io/$ORG_NAME/$SERVICE_NAME:latest
  size: $SIZE
  httpPort: $PORT
  healthPath: "/health"
  readyPath: "/ready"
  sessionAffinity: "None"
  # Secrets (update based on your service needs)
  secret1Name: ${SERVICE_NAME}-db-conn
  secret2Name: ${SERVICE_NAME}-cache-conn
  secret3Name: ${SERVICE_NAME}-config
EOF
echo -e "${GREEN}✓ overlays/dev/deployment.yaml${NC}"

cat > "$OVERLAYS_DIR/dev/migration-job.yaml" << EOF
# Database migration job - runs after database is ready, before app deployment
apiVersion: batch/v1
kind: Job
metadata:
  name: ${SERVICE_NAME}-migrations
  namespace: $NAMESPACE
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    metadata:
      name: ${SERVICE_NAME}-migrations
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-pull-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: migrations
        image: ghcr.io/$ORG_NAME/$SERVICE_NAME:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        command: ["./scripts/ci/run-migrations.sh"]
        envFrom:
        - secretRef:
            name: ${SERVICE_NAME}-db-conn
        env:
        - name: MIGRATION_DIR
          value: "/app/migrations"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  backoffLimit: 3
  activeDeadlineSeconds: 600
EOF
echo -e "${GREEN}✓ overlays/dev/migration-job.yaml${NC}"

# Create secrets kustomization placeholders
cat > "$OVERLAYS_DIR/dev/secrets/kustomization.yaml" << EOF
# Generated by: scripts/sync-ksops-secrets.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
- ksops-generator.yaml
EOF
echo -e "${GREEN}✓ overlays/dev/secrets/kustomization.yaml${NC}"

cat > "$OVERLAYS_DIR/dev/secrets/ksops-generator.yaml" << EOF
# Generated by: scripts/sync-ksops-secrets.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ${SERVICE_NAME}-dev-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
# Secret files will be added by sync-ksops-secrets.sh
EOF
echo -e "${GREEN}✓ overlays/dev/secrets/ksops-generator.yaml${NC}"

# Create staging overlay
echo -e "${BLUE}Creating staging overlay...${NC}"
cp -r "$OVERLAYS_DIR/dev" "$OVERLAYS_DIR/staging"
sed -i.bak 's/dev/staging/g' "$OVERLAYS_DIR/staging/kustomization.yaml"
sed -i.bak 's/dev/staging/g' "$OVERLAYS_DIR/staging/secrets/ksops-generator.yaml"
rm -f "$OVERLAYS_DIR/staging/kustomization.yaml.bak" "$OVERLAYS_DIR/staging/secrets/ksops-generator.yaml.bak"
echo -e "${GREEN}✓ overlays/staging/${NC}"

# Create production overlay
echo -e "${BLUE}Creating production overlay...${NC}"
cp -r "$OVERLAYS_DIR/dev" "$OVERLAYS_DIR/production"
sed -i.bak 's/dev/production/g' "$OVERLAYS_DIR/production/kustomization.yaml"
sed -i.bak 's/dev/production/g' "$OVERLAYS_DIR/production/secrets/ksops-generator.yaml"
rm -f "$OVERLAYS_DIR/production/kustomization.yaml.bak" "$OVERLAYS_DIR/production/secrets/ksops-generator.yaml.bak"
echo -e "${GREEN}✓ overlays/production/${NC}"

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Tenant Service Created Successfully                        ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
echo -e "${GREEN}✓ Location: $TENANT_DIR${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo -e "  1. Create .env file: ${GREEN}$TENANT_DIR/.env${NC}"
echo -e "  2. Add service secrets to .env (DEV_*, STAGING_*, PROD_* prefixed)"
echo -e "  3. Generate secrets: ${GREEN}cd $TENANT_REPO_PATH && ./scripts/sync-ksops-secrets.sh $SERVICE_NAME${NC}"
echo -e "  4. Review and commit changes"
echo ""
