apiVersion: v1
kind: Secret
metadata:
  name: github-pat
  namespace: intelligence-platform
type: Opaque
stringData:
  GITHUB_PERSONAL_ACCESS_TOKEN: "your-github-token-here"
---
# Instructions:
# 1. Replace "your-github-token-here" with your actual GitHub Personal Access Token
# 2. To create a GitHub PAT:
#    - Go to https://github.com/settings/tokens
#    - Click "Generate new token (classic)"
#    - Select scopes: repo, read:org, read:user
#    - Copy the token and replace the value above
# 3. Apply this secret: kubectl apply -f github-secret.yaml
