apiVersion: v1
kind: Service
metadata:
  name: qdrant-mcp
  namespace: intelligence-platform
  labels:
    app.kubernetes.io/name: qdrant-mcp
spec:
  selector:
    app.kubernetes.io/name: qdrant-mcp
  ports:
    - port: 8000
      targetPort: 8000
      name: http
