apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3-bucket
  labels:
    provider: aws
    crossplane.io/xrd: xobjectstorages.platform.bizmatters.io
spec:
  compositeTypeRef:
    apiVersion: platform.bizmatters.io/v1alpha1
    kind: XObjectStorage
  
  mode: Resources
  publishConnectionDetailsWithStoreConfigRef:
    name: default
    
  resources:
    # 1. S3 Bucket
    - name: s3-bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            region: ap-south-1
            forceDestroy: false
          deletionPolicy: Orphan
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.bucketName
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: status.bucketResourceName
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: metadata.labels[crossplane.io/external-name]
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"

    # 2. Bucket Versioning
    - name: bucket-versioning
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketVersioning
        spec:
          forProvider:
            region: ap-south-1
            bucket: ""
            versioningConfiguration:
              - status: Enabled
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: status.bucketName
          toFieldPath: spec.forProvider.bucket
          policy:
            fromFieldPath: Required
        - type: FromCompositeFieldPath
          fromFieldPath: spec.versioning
          toFieldPath: spec.forProvider.versioningConfiguration[0].status
          transforms:
            - type: convert
              convert:
                toType: string
            - type: map
              map:
                "true": Enabled
                "false": Suspended
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"
