apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3-bucket
  labels:
    provider: hetzner
    crossplane.io/xrd: xobjectstorages.platform.bizmatters.io
spec:
  compositeTypeRef:
    apiVersion: platform.bizmatters.io/v1alpha1
    kind: XObjectStorage
  
  mode: Resources
  publishConnectionDetailsWithStoreConfigRef:
    name: default
    
  resources:
    # 1. Bucket Name Generator (stores bucket name in status)
    - name: bucket-name
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: placeholder
                namespace: kube-system
              data:
                bucketName: ""
          providerConfigRef:
            name: kubernetes-provider
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.claimRef.name
              - fromFieldPath: spec.environment
            strategy: string
            string:
              fmt: "%s-%s"
          toFieldPath: spec.forProvider.manifest.data.bucketName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.manifest.metadata.name
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-bucket-name"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.forProvider.manifest.data.bucketName
          toFieldPath: status.bucketName
          policy:
            fromFieldPath: Optional
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"
              
    # 2. Connection Secret (Kubernetes Secret in target namespace with Hetzner S3 credentials)
    - name: connection-secret
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: placeholder
                namespace: placeholder
              type: Opaque
              stringData:
                S3_ENDPOINT: ""
                S3_REGION: ""
                S3_BUCKET: ""
                S3_ACCESS_KEY: ""
                S3_SECRET_KEY: ""
          references:
            - patchesFrom:
                apiVersion: v1
                kind: Secret
                name: hetzner-s3-endpoint
                namespace: kube-system
                fieldPath: data.value
              toFieldPath: stringData.S3_ENDPOINT
            - patchesFrom:
                apiVersion: v1
                kind: Secret
                name: hetzner-s3-region
                namespace: kube-system
                fieldPath: data.value
              toFieldPath: stringData.S3_REGION
            - patchesFrom:
                apiVersion: v1
                kind: Secret
                name: hetzner-s3-access-key
                namespace: kube-system
                fieldPath: data.value
              toFieldPath: stringData.S3_ACCESS_KEY
            - patchesFrom:
                apiVersion: v1
                kind: Secret
                name: hetzner-s3-secret-key
                namespace: kube-system
                fieldPath: data.value
              toFieldPath: stringData.S3_SECRET_KEY
          providerConfigRef:
            name: kubernetes-provider
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.manifest.metadata.name
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-conn"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.claimRef.name
              - fromFieldPath: spec.environment
            strategy: string
            string:
              fmt: "%s-%s"
          toFieldPath: spec.forProvider.manifest.stringData.S3_BUCKET
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"