# PVC removed - using emptyDir for testing
# Note: Data will not persist across pod restarts
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: intelligence-platform
spec:
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334
  selector:
    app: qdrant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: intelligence-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.16.0
          ports:
            - containerPort: 6333
              name: http
            - containerPort: 6334
              name: grpc
          volumeMounts:
            - name: storage
              mountPath: /qdrant/storage
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: storage
          emptyDir: {}  # Using emptyDir for testing (non-persistent)

