apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xagentsandboxnetworkings.platform.bizmatters.io
spec:
  group: platform.bizmatters.io
  names:
    kind: XAgentSandboxNetworking
    plural: xagentsandboxnetworkings
  claimNames:
    kind: AgentSandboxNetworking
    plural: agentsandboxnetworkings
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              claimRef:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
              httpPort:
                type: integer
                default: 8080
                minimum: 1
                maximum: 65535
              sessionAffinity:
                type: string
                enum: ["None", "ClientIP"]
                default: "None"
            required:
            - claimRef
          status:
            type: object
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  description: A Condition that may apply to a resource.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time this condition transitioned from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: A Message containing details about this condition's last transition from one status to another, if any.
                      type: string
                    reason:
                      description: A Reason for this condition's last transition from one status to another.
                      type: string
                    status:
                      description: Status of this condition; is it currently True, False, or Unknown?
                      type: string
                    type:
                      description: Type of this condition. At most one of each condition type may apply to a resource at any point in time.
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array