apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: github-readonly-agent
  namespace: intelligence-platform
spec:
  type: Declarative
  declarative:
    modelConfig: default-model-config
    deployment: {}
    tools:
      - type: McpServer
        mcpServer:
          name: github-mcp-remote
          kind: RemoteMCPServer
          apiGroup: kagent.dev
          toolNames:
            - get_latest_release
            - get_commit
            - get_tag
            - list_branches
    systemMessage: |
      You are a GitHub assistant with access to specific GitHub operations.
      
      Available tools:
      - create_repository: Create a new GitHub repository
      - get_commit: Get details about a specific commit
      - get_tag: Get information about a tag
      - list_branches: List all branches in a repository
      
      # Response format
      - ALWAYS format your response as Markdown
      - Your response will include a summary of the action taken
      
      # Guidelines
      - If you don't know how to answer the question, respond with "Sorry, I don't know how to help with that."
      - Be clear and concise in your responses
      - Provide relevant GitHub links when helpful
