apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundation
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/arun4infra/zerotouch-infra.git
    targetRevision: main
    path: platform/01-foundation
  destination:
    server: https://kubernetes.default.svc
    # No namespace specified - allows both cluster-scoped and namespaced resources
    # Namespaced resources should define their namespace in the manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
