---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: age-key-guardian
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: age-key-guardian
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["sops-age", "age-backup-encrypted", "recovery-master-key"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: age-key-guardian
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: age-key-guardian
subjects:
  - kind: ServiceAccount
    name: age-key-guardian
    namespace: argocd
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: age-key-guardian
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: age-key-guardian
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: guardian
              image: alpine:3.19
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  
                  # Install dependencies
                  apk add --no-cache bash curl kubectl age jq
                  
                  # Execute recovery logic
                  exec bash -c '
                  set -euo pipefail
                  
                  echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] Age Key Guardian starting..."
                  
                  # Check if sops-age secret exists
                  if kubectl get secret sops-age -n argocd &>/dev/null; then
                    echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] ✓ sops-age secret exists - no action needed"
                    exit 0
                  fi
                  
                  echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] ⚠ sops-age secret missing - initiating recovery"
                  
                  # Check if backup exists
                  if ! kubectl get secret age-backup-encrypted -n argocd &>/dev/null; then
                    echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] ✗ ERROR: age-backup-encrypted secret not found"
                    exit 1
                  fi
                  
                  if ! kubectl get secret recovery-master-key -n argocd &>/dev/null; then
                    echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] ✗ ERROR: recovery-master-key secret not found"
                    exit 1
                  fi
                  
                  # Extract encrypted backup and recovery key
                  ENCRYPTED_BACKUP=$(kubectl get secret age-backup-encrypted -n argocd -o jsonpath="{.data.encrypted-key\.txt}" | base64 -d)
                  RECOVERY_KEY=$(kubectl get secret recovery-master-key -n argocd -o jsonpath="{.data.recovery-key\.txt}" | base64 -d)
                  
                  # Decrypt the Age key
                  echo "$ENCRYPTED_BACKUP" | age -d -i <(echo "$RECOVERY_KEY") > /tmp/keys.txt
                  
                  if [ ! -s /tmp/keys.txt ]; then
                    echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] ✗ ERROR: Failed to decrypt Age key"
                    exit 1
                  fi
                  
                  # Restore sops-age secret
                  kubectl create secret generic sops-age \
                    --from-file=keys.txt=/tmp/keys.txt \
                    --namespace=argocd \
                    --dry-run=client -o yaml | kubectl apply -f -
                  
                  echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] ✓ sops-age secret restored successfully"
                  
                  # Send Slack alert if webhook configured
                  if [ -n "${SLACK_WEBHOOK_URL:-}" ]; then
                    curl -s -X POST "$SLACK_WEBHOOK_URL" \
                      -H "Content-Type: application/json" \
                      -d "{\"attachments\":[{\"color\":\"#36a64f\",\"text\":\"🔑 Age Key Guardian: Restored missing sops-age secret in argocd namespace\"}]}" \
                      || echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] ⚠ Failed to send Slack alert"
                  else
                    echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] ℹ SLACK_WEBHOOK_URL not set - skipping alert"
                  fi
                  
                  # Clean up
                  rm -f /tmp/keys.txt
                  
                  echo "[$(date -u +"%Y-%m-%d %H:%M:%S UTC")] Age Key Guardian completed"
                  '
              env:
                - name: SLACK_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: slack-webhook
                      key: url
                      optional: true
              volumeMounts:
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                capabilities:
                  drop:
                    - ALL
