apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: xdg-config
          emptyDir: {}
        - name: sops-age-key
          secret:
            secretName: sops-age
            optional: true
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.3.2
          command: ["/bin/sh", "-c"]
          args:
            - echo "Installing KSOPS...";
              cp /usr/local/bin/kustomize /custom-tools/;
              mkdir -p /.config/kustomize/plugin/viaduct.ai/v1/ksops;
              cp /usr/local/bin/ksops /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops;
              echo "Done.";
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
            - mountPath: /.config
              name: xdg-config
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
            - mountPath: /.config
              name: xdg-config
            - mountPath: /.config/sops/age
              name: sops-age-key
          env:
            - name: XDG_CONFIG_HOME
              value: /.config
            - name: SOPS_AGE_KEY_FILE
              value: /.config/sops/age/keys.txt
            - name: PATH
              value: /custom-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
