apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      initContainers:
      - name: install-ksops
        image: viaductoss/ksops:v4.3.2
        command: ["/bin/sh", "-c"]
        args:
          - echo "Installing KSOPS...";
            cp /usr/local/bin/ksops /custom-tools/;
            cp /usr/local/bin/kustomize /custom-tools/;
            echo "Done.";
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
      containers:
      - name: ksops
        image: quay.io/argoproj/argocd:v3.2.0
        command:
          - /var/run/argocd/argocd-cmp-server
        env:
          - name: SOPS_AGE_KEY_FILE
            value: /home/argocd/.config/sops/age/keys.txt
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: 1000m
            memory: 512Mi
            ephemeral-storage: 2Gi
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - name: var-files
            mountPath: /var/run/argocd
          - name: cmp-plugin
            mountPath: /home/argocd/cmp-server/plugins/plugin.yaml
            subPath: plugin.yaml
          - name: cmp-tmp
            mountPath: /tmp
          - name: sops-age-key
            mountPath: /home/argocd/.config/sops/age
            readOnly: true
          - name: custom-tools
            mountPath: /usr/local/bin/ksops
            subPath: ksops
          - name: custom-tools
            mountPath: /usr/local/bin/kustomize
            subPath: kustomize
      volumes:
      - name: var-files
        emptyDir: {}
      - name: cmp-plugin
        configMap:
          name: cmp-plugin
      - name: cmp-tmp
        emptyDir: {}
      - name: sops-age-key
        secret:
          secretName: sops-age
          optional: true
      - name: custom-tools
        emptyDir: {}
