apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-kubernetes-provider
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - configmaps
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - keda.sh
    resources:
      - scaledobjects
    verbs:
      - "*"
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
      - backups
      - scheduledbackups
      - poolers
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-kubernetes-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-kubernetes-provider
subjects:
  - kind: ServiceAccount
    name: provider-kubernetes-6ef2ebb6f1db
    namespace: crossplane-system
