apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: agent-sandbox-service-main
  labels:
    provider: kubernetes
    crossplane.io/xrd: xagentsandboxservices.platform.bizmatters.io
spec:
  compositeTypeRef:
    apiVersion: platform.bizmatters.io/v1alpha1
    kind: XAgentSandboxService

  mode: Resources
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  resources:
    # Component 1: ServiceAccount
    - name: serviceaccount-component
      base:
        apiVersion: platform.bizmatters.io/v1alpha1
        kind: XAgentSandboxServiceAccount
        spec:
          claimRef:
            apiVersion: platform.bizmatters.io/v1alpha1
            kind: AgentSandboxServiceAccount
            name: placeholder
            namespace: placeholder
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.claimRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.claimRef.namespace
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"

    # Component 2: Storage (PVC)
    - name: storage-component
      base:
        apiVersion: platform.bizmatters.io/v1alpha1
        kind: XAgentSandboxStorage
        spec:
          claimRef:
            apiVersion: platform.bizmatters.io/v1alpha1
            kind: AgentSandboxStorage
            name: placeholder
            namespace: placeholder
          storageGB: 10
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.claimRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.claimRef.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.storageGB
          toFieldPath: spec.storageGB
          policy:
            fromFieldPath: Optional
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"

    # Component 3: Core Sandbox (depends on storage)
    - name: sandbox-component
      base:
        apiVersion: platform.bizmatters.io/v1alpha1
        kind: XAgentSandboxCore
        spec:
          claimRef:
            apiVersion: platform.bizmatters.io/v1alpha1
            kind: AgentSandboxCore
            name: placeholder
            namespace: placeholder
          image: placeholder
          nats:
            url: placeholder
            stream: placeholder
            consumer: placeholder
          httpPort: 8080
          size: medium
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.claimRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.claimRef.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.image
          toFieldPath: spec.image
        - type: FromCompositeFieldPath
          fromFieldPath: spec.command
          toFieldPath: spec.command
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.args
          toFieldPath: spec.args
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.size
          toFieldPath: spec.size
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.nats
          toFieldPath: spec.nats
        - type: FromCompositeFieldPath
          fromFieldPath: spec.httpPort
          toFieldPath: spec.httpPort
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.healthPath
          toFieldPath: spec.healthPath
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.readyPath
          toFieldPath: spec.readyPath
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.imagePullSecrets
          toFieldPath: spec.imagePullSecrets
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.secret1Name
          toFieldPath: spec.secret1Name
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.secret2Name
          toFieldPath: spec.secret2Name
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.secret3Name
          toFieldPath: spec.secret3Name
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.secret4Name
          toFieldPath: spec.secret4Name
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.secret5Name
          toFieldPath: spec.secret5Name
          policy:
            fromFieldPath: Optional
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"

    # Component 4: Networking (HTTP Service)
    - name: networking-component
      base:
        apiVersion: platform.bizmatters.io/v1alpha1
        kind: XAgentSandboxNetworking
        spec:
          claimRef:
            apiVersion: platform.bizmatters.io/v1alpha1
            kind: AgentSandboxNetworking
            name: placeholder
            namespace: placeholder
          httpPort: 8080
          sessionAffinity: None
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.claimRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.claimRef.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.httpPort
          toFieldPath: spec.httpPort
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.sessionAffinity
          toFieldPath: spec.sessionAffinity
          policy:
            fromFieldPath: Optional
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"

    # Component 5: Scaling (KEDA)
    - name: scaling-component
      base:
        apiVersion: platform.bizmatters.io/v1alpha1
        kind: XAgentSandboxScaling
        spec:
          claimRef:
            apiVersion: platform.bizmatters.io/v1alpha1
            kind: AgentSandboxScaling
            name: placeholder
            namespace: placeholder
          nats:
            stream: placeholder
            consumer: placeholder
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.claimRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.claimRef.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.nats.stream
          toFieldPath: spec.nats.stream
        - type: FromCompositeFieldPath
          fromFieldPath: spec.nats.consumer
          toFieldPath: spec.nats.consumer
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"

    # Component 6: Connection Secret
    - name: connection-component
      base:
        apiVersion: platform.bizmatters.io/v1alpha1
        kind: XAgentSandboxConnection
        spec:
          claimRef:
            apiVersion: platform.bizmatters.io/v1alpha1
            kind: AgentSandboxConnection
            name: placeholder
            namespace: placeholder
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.claimRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.claimRef.namespace
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"