apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeventdrivenservices.platform.bizmatters.io
spec:
  group: platform.bizmatters.io
  names:
    kind: XEventDrivenService
    plural: xeventdrivenservices
  claimNames:
    kind: EventDrivenService
    plural: eventdrivenservices
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "EventDrivenService specification for deploying NATS JetStream consumer services with KEDA autoscaling"
              required:
                - image
                - nats
              properties:
                image:
                  type: string
                  description: "Container image reference (registry/repository:tag or registry/repository@sha256:digest)"
                  pattern: '^[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}|@sha256:[a-f0-9]{64})?$'
                  example: "ghcr.io/org/my-service:v1.0.0"

                size:
                  type: string
                  description: "Resource size allocation (micro: 100m-500m CPU, 256Mi-1Gi memory; small: 250m-1000m CPU, 512Mi-2Gi memory; medium: 500m-2000m CPU, 1Gi-4Gi memory; large: 1000m-4000m CPU, 2Gi-8Gi memory)"
                  enum:
                    - micro
                    - small
                    - medium
                    - large
                  default: medium

                nats:
                  type: object
                  description: "NATS JetStream configuration"
                  required:
                    - stream
                    - consumer
                  properties:
                    url:
                      type: string
                      description: "NATS server URL for client connections"
                      default: "nats://nats.nats.svc:4222"
                      pattern: '^nats://[a-z0-9.-]+:[0-9]+$'

                    stream:
                      type: string
                      description: "JetStream stream name (must exist before deployment)"
                      minLength: 1
                      maxLength: 255
                      pattern: '^[A-Z0-9_]+$'
                      example: "AGENT_EXECUTION"

                    consumer:
                      type: string
                      description: "Consumer group name for this service"
                      minLength: 1
                      maxLength: 255
                      pattern: '^[a-z0-9-]+$'
                      example: "agent-executor-workers"

                # Pre-defined secret slots (envFrom only - bulk mounting)
                # This approach avoids dynamic array iteration limitations in Crossplane
                # Fully supports Hybrid Secret Sources (Crossplane + ESO) without consolidation
                # All secret keys are mounted as environment variables using envFrom
                
                secret1Name:
                  type: string
                  description: "First secret name to mount via envFrom (typically database credentials)"
                  minLength: 1
                  maxLength: 253
                  pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                  example: "my-service-db-conn"

                secret2Name:
                  type: string
                  description: "Second secret name to mount via envFrom (typically cache credentials)"
                  minLength: 1
                  maxLength: 253
                  pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                  example: "my-service-cache-conn"

                secret3Name:
                  type: string
                  description: "Third secret name to mount via envFrom (typically application secrets)"
                  minLength: 1
                  maxLength: 253
                  pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                  example: "my-service-llm-keys"

                secret4Name:
                  type: string
                  description: "Fourth secret name to mount via envFrom (optional)"
                  minLength: 1
                  maxLength: 253
                  pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'

                secret5Name:
                  type: string
                  description: "Fifth secret name to mount via envFrom (optional)"
                  minLength: 1
                  maxLength: 253
                  pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'

                imagePullSecrets:
                  type: array
                  description: "Array of image pull secret names for private container registries"
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        description: "Name of the image pull secret"
                        minLength: 1
                        maxLength: 253
                        pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                        example: "ghcr-pull-secret"

                # HTTP endpoint configuration (optional - enables HTTP/WebSocket alongside NATS)
                httpPort:
                  type: integer
                  description: "HTTP port for REST/WebSocket endpoints (optional - if specified, creates HTTP Service)"
                  minimum: 1
                  maximum: 65535
                  example: 8000

                healthPath:
                  type: string
                  description: "Health check endpoint path (only when httpPort specified)"
                  default: "/health"
                  pattern: '^\/.*'
                  example: "/health"

                readyPath:
                  type: string
                  description: "Readiness check endpoint path (only when httpPort specified)"
                  default: "/ready"
                  pattern: '^\/.*'
                  example: "/ready"

                sessionAffinity:
                  type: string
                  description: "Session affinity for HTTP service (only when httpPort specified)"
                  enum: ["None", "ClientIP"]
                  default: "None"

                initContainer:
                  type: object
                  description: "Optional init container configuration for database migrations or pre-start tasks (uses same image as main container)"
                  required:
                    - command
                  properties:
                    command:
                      type: array
                      description: "Command to execute in the init container"
                      minItems: 1
                      items:
                        type: string
                      example: ["/bin/bash", "-c"]

                    args:
                      type: array
                      description: "Arguments to pass to the command"
                      items:
                        type: string
                      example: ["cd /app && ./scripts/ci/run-migrations.sh"]
