#!/bin/bash
# Generate tenant secrets (GitHub App credentials for ArgoCD)

set -e

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
ENV_FILE="$REPO_ROOT/.env"
OVERLAYS_DIR="$REPO_ROOT/bootstrap/argocd/overlays/main"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

set -a
source "$ENV_FILE"
set +a

REGISTRY_SECRETS_DIR="$OVERLAYS_DIR/registry"
CORE_SECRETS_DIR="$OVERLAYS_DIR/core/secrets"

echo -e "${BLUE}Processing TENANT secrets...${NC}"

mkdir -p "$REGISTRY_SECRETS_DIR"
mkdir -p "$CORE_SECRETS_DIR"

if [ -d "$REGISTRY_SECRETS_DIR" ]; then
    find "$REGISTRY_SECRETS_DIR" -name "*.secret.yaml" -type f -delete
fi

# ArgoCD repo secret
if [[ -n "$ORG_NAME" && -n "$TENANTS_REPO_NAME" && -n "$GITHUB_APP_ID" && -n "$GITHUB_APP_INSTALLATION_ID" && -n "$GITHUB_APP_PRIVATE_KEY" ]]; then
    REPO_URL="https://github.com/${ORG_NAME}/${TENANTS_REPO_NAME}.git"
    
    cat > "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml" << 'EOF'
apiVersion: v1
kind: Secret
metadata:
  name: repo-zerotouch-tenants
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  type: git
EOF
    
    echo "  url: ${REPO_URL}" >> "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    echo "  githubAppID: \"${GITHUB_APP_ID}\"" >> "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    echo "  githubAppInstallationID: \"${GITHUB_APP_INSTALLATION_ID}\"" >> "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    echo "  githubAppPrivateKey: |" >> "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    echo "$GITHUB_APP_PRIVATE_KEY" | sed 's/^/    /' >> "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    
    if sops -e -i "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml" 2>/dev/null; then
        echo -e "${GREEN}  ✓ repo-zerotouch-tenants.secret.yaml${NC}"
        
        # Create KSOPS Generator
        cat > "$REGISTRY_SECRETS_DIR/ksops-generator.yaml" << EOF
# Generated by: scripts/bootstrap/infra/secrets/ksops/generate-sops/generate-tenant-registry-secrets.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: registry-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./repo-zerotouch-tenants.secret.yaml
EOF
        
        # Create Kustomization with generator
        cat > "$REGISTRY_SECRETS_DIR/kustomization.yaml" << EOF
# Generated by: scripts/bootstrap/infra/secrets/ksops/generate-sops/generate-tenant-registry-secrets.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
- ksops-generator.yaml
EOF
        echo -e "${GREEN}  ✓ kustomization.yaml (KSOPS generator)${NC}"
    else
        echo -e "${RED}  ✗ Failed to encrypt: repo-zerotouch-tenants.secret.yaml${NC}"
        rm -f "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    fi
else
    echo -e "${YELLOW}  ⚠️  Skipping ArgoCD repo secret (missing credentials)${NC}"
fi

# GHCR pull secret (initial bootstrap only)
# This creates the initial ghcr-pull-secret in the registry overlay for first deployment
# After deployment, platform/foundation/ghcr-token-refresher/cronjob.yaml automatically
# refreshes this secret every 30 minutes in all tenant namespaces using github-app-credentials
if [[ -n "$GITHUB_APP_ID" && -n "$GITHUB_APP_INSTALLATION_ID" && -n "$GITHUB_APP_PRIVATE_KEY" ]]; then
    # Generate JWT for GitHub App
    NOW=$(date +%s)
    IAT=$((NOW - 60))
    EXP=$((NOW + 600))
    
    HEADER='{"alg":"RS256","typ":"JWT"}'
    PAYLOAD="{\"iat\":${IAT},\"exp\":${EXP},\"iss\":\"${GITHUB_APP_ID}\"}"
    
    HEADER_B64=$(echo -n "$HEADER" | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
    PAYLOAD_B64=$(echo -n "$PAYLOAD" | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
    
    SIGNATURE=$(echo -n "${HEADER_B64}.${PAYLOAD_B64}" | openssl dgst -sha256 -sign <(echo "$GITHUB_APP_PRIVATE_KEY") | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
    JWT="${HEADER_B64}.${PAYLOAD_B64}.${SIGNATURE}"
    
    # Get installation access token
    TOKEN_RESPONSE=$(curl -s -X POST \
        -H "Authorization: Bearer $JWT" \
        -H "Accept: application/vnd.github+json" \
        "https://api.github.com/app/installations/${GITHUB_APP_INSTALLATION_ID}/access_tokens")
    
    GITHUB_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.token // empty')
    
    if [ -n "$GITHUB_TOKEN" ]; then
        # Create dockerconfigjson auth string
        AUTH_STRING=$(echo -n "x-access-token:${GITHUB_TOKEN}" | base64)
        
        cat > "$REGISTRY_SECRETS_DIR/ghcr-pull-secret.secret.yaml" << EOF
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "${AUTH_STRING}"
        }
      }
    }
EOF
        
        if sops -e -i "$REGISTRY_SECRETS_DIR/ghcr-pull-secret.secret.yaml" 2>/dev/null; then
            echo -e "${GREEN}  ✓ ghcr-pull-secret.secret.yaml${NC}"
            
            # Update KSOPS generator to include GHCR secret
            cat > "$REGISTRY_SECRETS_DIR/ksops-generator.yaml" << EOF
# Generated by: scripts/bootstrap/infra/secrets/ksops/generate-sops/generate-tenant-registry-secrets.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: registry-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./repo-zerotouch-tenants.secret.yaml
  - ./ghcr-pull-secret.secret.yaml
EOF
        else
            echo -e "${RED}  ✗ Failed to encrypt: ghcr-pull-secret.secret.yaml${NC}"
            rm -f "$REGISTRY_SECRETS_DIR/ghcr-pull-secret.secret.yaml"
        fi
    else
        echo -e "${RED}  ✗ Failed to generate GitHub App token${NC}"
    fi
else
    echo -e "${YELLOW}  ⚠️  Skipping GHCR pull secret (missing credentials)${NC}"
fi

echo ""
