#!/bin/bash
# Generate tenant secrets (GitHub App credentials for ArgoCD)

set -e

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
ENV_FILE="$REPO_ROOT/.env"
OVERLAYS_DIR="$REPO_ROOT/bootstrap/argocd/overlays/main"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

set -a
source "$ENV_FILE"
set +a

REGISTRY_SECRETS_DIR="$OVERLAYS_DIR/registry"
CORE_SECRETS_DIR="$OVERLAYS_DIR/core/secrets"

echo -e "${BLUE}Processing TENANT secrets...${NC}"

mkdir -p "$REGISTRY_SECRETS_DIR"
mkdir -p "$CORE_SECRETS_DIR"

if [ -d "$REGISTRY_SECRETS_DIR" ]; then
    find "$REGISTRY_SECRETS_DIR" -name "*.secret.yaml" -type f -delete
fi

# ArgoCD repo secret
if [[ -n "$ORG_NAME" && -n "$TENANTS_REPO_NAME" && -n "$GITHUB_APP_ID" && -n "$GITHUB_APP_INSTALLATION_ID" && -n "$GITHUB_APP_PRIVATE_KEY" ]]; then
    REPO_URL="https://github.com/${ORG_NAME}/${TENANTS_REPO_NAME}.git"
    
    cat > "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml" << 'EOF'
apiVersion: v1
kind: Secret
metadata:
  name: repo-zerotouch-tenants
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  type: git
EOF
    
    echo "  url: ${REPO_URL}" >> "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    echo "  githubAppID: \"${GITHUB_APP_ID}\"" >> "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    echo "  githubAppInstallationID: \"${GITHUB_APP_INSTALLATION_ID}\"" >> "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    echo "  githubAppPrivateKey: |" >> "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    echo "$GITHUB_APP_PRIVATE_KEY" | sed 's/^/    /' >> "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    
    if sops -e -i "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml" 2>/dev/null; then
        echo -e "${GREEN}  ✓ repo-zerotouch-tenants.secret.yaml${NC}"
        
        # Create KSOPS Generator
        cat > "$REGISTRY_SECRETS_DIR/ksops-generator.yaml" << EOF
# Generated by: scripts/bootstrap/infra/secrets/ksops/generate-sops/generate-tenant-registry-secrets.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: registry-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./repo-zerotouch-tenants.secret.yaml
EOF
        
        # Create Kustomization with generator
        cat > "$REGISTRY_SECRETS_DIR/kustomization.yaml" << EOF
# Generated by: scripts/bootstrap/infra/secrets/ksops/generate-sops/generate-tenant-registry-secrets.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
- ksops-generator.yaml
EOF
        echo -e "${GREEN}  ✓ kustomization.yaml (KSOPS generator)${NC}"
    else
        echo -e "${RED}  ✗ Failed to encrypt: repo-zerotouch-tenants.secret.yaml${NC}"
        rm -f "$REGISTRY_SECRETS_DIR/repo-zerotouch-tenants.secret.yaml"
    fi
else
    echo -e "${YELLOW}  ⚠️  Skipping ArgoCD repo secret (missing credentials)${NC}"
fi

echo ""
