apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: agentsandbox-serviceaccount
  labels:
    provider: kubernetes
    component: serviceaccount
    crossplane.io/xrd: xagentsandboxserviceaccounts.platform.bizmatters.io
spec:
  compositeTypeRef:
    apiVersion: platform.bizmatters.io/v1alpha1
    kind: XAgentSandboxServiceAccount

  mode: Resources
  resources:
    # ServiceAccount Resource
    - name: serviceaccount
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: placeholder
                namespace: placeholder
                labels:
                  app.kubernetes.io/name: placeholder
                  app.kubernetes.io/component: agent-sandbox
                  app.kubernetes.io/managed-by: crossplane
              automountServiceAccountToken: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.manifest.metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.manifest.metadata.labels[app.kubernetes.io/name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"