apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: agentsandbox-storage
  labels:
    provider: kubernetes
    component: storage
    crossplane.io/xrd: xagentsandboxstorages.platform.bizmatters.io
spec:
  compositeTypeRef:
    apiVersion: platform.bizmatters.io/v1alpha1
    kind: XAgentSandboxStorage

  mode: Resources
  resources:
    # PersistentVolumeClaim Resource (Managed by Crossplane)
    - name: workspace-pvc
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          # Delete on claim deletion to allow "Cold" state (S3 only)
          deletionPolicy: Delete
          forProvider:
            manifest:
              apiVersion: v1
              kind: PersistentVolumeClaim
              metadata:
                name: placeholder-workspace
                namespace: placeholder
                labels:
                  app.kubernetes.io/name: placeholder
                  app.kubernetes.io/component: agent-sandbox
                  app.kubernetes.io/managed-by: crossplane
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: "10Gi"
                storageClassName: "local-path"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.manifest.metadata.name
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-workspace"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.manifest.metadata.labels[app.kubernetes.io/name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.storageGB
          toFieldPath: spec.forProvider.manifest.spec.resources.requests.storage
          transforms:
            - type: string
              string:
                type: Format
                fmt: "%dGi"
          policy:
            fromFieldPath: Optional
      readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Ready
            status: "True"
        - type: MatchString
          fieldPath: "status.atProvider.manifest.status.phase"
          matchString: "Bound"  # Re-creation triggers if state is not 'Bound' (e.g., missing)