apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-access-token
            key: AWS_ACCESS_KEY_ID
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-access-token
            key: AWS_SECRET_ACCESS_KEY
            namespace: external-secrets
          # Optional: Session token for temporary credentials (OIDC/STS)
          # ESO will use this if the key exists in the secret
          sessionTokenSecretRef:
            name: aws-access-token
            key: AWS_SESSION_TOKEN
            namespace: external-secrets
