#!/usr/bin/env bash
# Reporter helper - generates migration report

generate_migration_report() {
    echo ""
    echo "=== Migration Report ==="
    echo ""
    echo "GitHub App Configuration:"
    echo "  App ID: ${APP_ID}"
    echo "  Installation ID: ${INSTALLATION_ID}"
    echo "  Private Key: ${PRIVATE_KEY_FILE}"
    echo ""
    echo "Backup:"
    echo "  Local backup: ${BACKUP_FILE}"
    echo "  Cluster backup: repo-pat-backup-* secrets in argocd namespace"
    echo ""
    echo "Updated Secrets:"
    local repo_secrets=$(kubectl get secret -n argocd -l argocd.argoproj.io/secret-type=repository -o name | wc -l)
    echo "  ${repo_secrets} repository credential(s) updated"
    echo ""
    echo "Next Steps:"
    echo "  1. ✓ Verify ArgoCD can sync applications"
    echo "  2. ✓ Update GitHub Actions workflows to use GitHub App"
    echo "  3. ✓ Test auto-merge with branch protection bypass"
    echo "  4. ✓ Keep PAT in GitHub Secrets as fallback"
    echo "  5. ✓ Document rollback procedure"
    echo ""
    echo "Emergency Rollback:"
    echo "  kubectl apply -f ${BACKUP_FILE}"
    echo "  kubectl delete secret argocd-github-app-creds -n argocd"
    echo ""
    echo "Verification Checklist:"
    echo "  [ ] ArgoCD UI shows green repository status"
    echo "  [ ] Test application sync succeeds"
    echo "  [ ] GitHub Actions can create PRs with GitHub App token"
    echo "  [ ] Auto-merge works with branch protection bypass"
    echo "  [ ] PAT preserved in GitHub Secrets"
    echo ""
}
